### ISSUE TITLE
Confusion about purpose of this library

### ISSUE THREAD

**Issue by novaterata** [okta/okta-jwt-verifier-java#14]
I was hoping this library would be usable as a general purpose JWT verifier, but it seems to only work with okta. Is that the intention? If so than please clarify this. If not then I have a few bugs that are blockers for me.

**Comment by novaterata** [comment]
In particular, validating a JWT from Azure fails because the issuer URL ends in a trailing slash, yet when I set the issuerURL this library always trims the trailing slash because okta doesn't use one. So the validation always fails.

**Comment by novaterata** [comment]
I've worked around it by replicating the JwtHelper builder and replacing the Okta validator with the generic one.

**Comment by bdemers** [comment]
@novaterata Yes the intention is to provide an Okta specific lib.
