### ISSUE TITLE
Using beginner example: "Caused by: com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found"

### ISSUE THREAD

**Issue by kiplaaang** [okta/okta-jwt-verifier-java#21]
I was originally using my own implementation of a JWT verifier based on nimbus' jwt jose library, but kept getting "com.nimbusds.jwt.SignedJWT@4dc6c945 : Signed JWT rejected: Another algorithm expected, or no matching key(s) found"

So I found this library, and followed the example on the first page https://github.com/okta/okta-jwt-verifier-java

I get the same exception. code is currently: 

        JwtVerifier jwtVerifier = new JwtHelper()
            .setIssuerUrl("https://dev-******.oktapreview.com/oauth2/default")
            .setAudience("api://default")  // defaults to 'api://default'
            .setConnectionTimeout(1000)    // defaults to 1000ms
            .setReadTimeout(1000)          // defaults to 1000ms
            .setClientId("******") // optional
            .build();

        String accessToken = "eyJ******";
        Jwt jwt = jwtVerifier.decodeAccessToken(accessToken);

And fails on "build". I've masked my okta domain and client id and accessToken. I don't see how I can make this simpler than this. Maybe my Okta config is wrong?

Exception is:
Exception in thread "main" com.okta.jwt.JoseException: Failed to validate JWT string
	at com.okta.jwt.impl.NimbusJwtVerifier.decode(NimbusJwtVerifier.java:82)
	at com.okta.jwt.impl.NimbusJwtVerifier.decodeAccessToken(NimbusJwtVerifier.java:68)
	at veeva.vdm.auth.core.Sandbox.main(Sandbox.java:31)
Caused by: com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.<clinit>(DefaultJWTProcessor.java:100)
	at com.okta.jwt.JwtHelper.build(JwtHelper.java:92)
	at veeva.vdm.auth.core.Sandbox.main(Sandbox.java:23)

Additional note: I am using the following tool to get the accessToken to test with: https://oidcdebugger.com/

**Comment by kiplaaang** [comment]
I just now tried using https://jwt.io/ to validate the token I got... and it says invalid token. Not sure why. 

Will try getting an access token in a different way maybe? I tried last week validating the tokens and it seemed fine then. Not sure why it's an issue now

**Comment by bdemers** [comment]
@kiplaaang Thanks for following up!
This is related to #13, we will try to get a more descriptive error message when this happens
