### ISSUE TITLE
Issuer URL cannot be set to other than URI

### ISSUE THREAD

**Issue by ImJezz** [okta/okta-jwt-verifier-java#28]
When you are using Google+ API for sign in using Oauth2 it can return both an URI or a string, in the OktaJWTClaimsVerifier it would be an improvement to check if the issuer is either URI or URI-link substring https://, or is there another workaround for this?

`https://accounts.google.com` this is required for the JWTHelper to be an URI
`accounts.google.com` what google actually can return as well

**Comment by bdemers** [comment]
@ImJezz sorry for the delay (I had my notifications miss-configured for this repo)
Are you trying to use this lib with Google's tokens or Okta configured to use Google as an IdP?

**Comment by bdemers** [comment]
I'll take a look, and try to reproduce this!

**Comment by bdemers** [comment]
@ImJezz How are you getting the token? directly from Google or via Okta?

**Comment by ImJezz** [comment]
> @ImJezz How are you getting the token? directly from Google or via Okta?

I guess from Google, 
when you click Sign in you get redirect to Google Login and then that token is set.

**Comment by ImJezz** [comment]
Hmm, what kind of sign in widget do you use? I used one that maybe didn't have a connection to Okta

**Comment by bdemers** [comment]
Typically Okta's SignIn Widget (or an oauth redirect).

Are you using Google products and Okta for SSO (meaning the all of the flows are initiated from Google)?

**Comment by ImJezz** [comment]
Yeah that seems to be the case, can you show me your sign-in widget because I have found the wrong one to use then. Thanks for help 👍

**Comment by bdemers** [comment]
Here you go: https://github.com/okta/okta-signin-widget

You can also use a simple redirect (and customize the login page via your Okta admin console)
