### ISSUE TITLE
Security vulnerability with required library, njwt

### ISSUE THREAD

**Issue by subukamath** [okta/okta-jwt-verifier-java#35]
We are using the below version of the library.

"@okta/jwt-verifier": {
			"version": "0.0.14",
			"resolved": "https://registry.npmjs.org/@okta/jwt-verifier/-/jwt-verifier-0.0.14.tgz",
			"integrity": "sha512-O+CzOeMy6aUi0PtqmoZLmKjE1xpUF9nUMlZ3hYlz4fUpb3zKUUESohq/iSuBijw2dB0Lru6Tsi7OWJXFJT1vew==",
			"requires": {
				"@okta/configuration-validation": "^0.1.1",
				"jwks-rsa": "^1.2.0",
				"njwt": "^0.4.0"
			}
		}

The version of njwt used has been flagged with a Uninitialized Buffer Allocation Vulnerability.
https://www.sourceclear.com/vulnerability-database/security/sca/vulnerability/sid-6814/summary

Please can you review and use a new version of the library or use a different one so that the issue is resolved?

**Comment by bdemers** [comment]
Thanks @subukamath 
This isn't the best way to report a security issue, Apache has a nice generic writeup: https://www.apache.org/security/
And Okta has one too: https://www.okta.com/vulnerability-reporting-policy/

That said, this is the wrong repo to report this against, but i'll pass the word along

**Comment by nbarbettini** [comment]
For anyone wondering, the repo for the `@okta/jwt-verifier` package is https://github.com/okta/okta-oidc-js

And we're patching the vulnerabilities there: https://github.com/okta/okta-oidc-js/issues/385
