### ISSUE TITLE
 RemoteJwkSigningKeyResolver updateKeys() returns null map despite key being retrieved

### ISSUE THREAD

**Issue by Aniczka** [okta/okta-jwt-verifier-java#45]
This specific method returns null map which was resulting in following exception: `java.lang.IllegalArgumentException`: A signing key must be specified if the specified JWT is digitally signed. I could see in debug mode that the key is retrieved and should pass both filters (sig - public key use, RSA - key type) and go into .map/.collect. This wasn't happening. I copied the code into my own java class, was trying to work out whenever i had a free moment and the problem lies with collection to map. it just cannot see the key and value of AbstractMap this way. I got it working in my local code but obviously this needs to be fixed on library level.  This is my fixed code:
```java
Map<String, Key> newKeys = (Map) keys.stream()
    .filter(jwkKey -> "sig".equals(jwkKey.getPublicKeyUse()) && 
        "RSA".equals(jwkKey.getKeyType()))
    .collect(Collectors.toMap(key -> key.getKeyId(), key -> {
        BigInteger modulus = base64ToBigInteger(key.getPublicKeyModulus());
        BigInteger exponent = base64ToBigInteger(key.getPublicKeyExponent());
        RSAPublicKeySpec rsaPublicKeySpec = new RSAPublicKeySpec(modulus, exponent);
        try {
            KeyFactory keyFactory = KeyFactory.getInstance("RSA");
            PublicKey publicKey = keyFactory.generatePublic(rsaPublicKeySpec);
            return publicKey;
        } catch (InvalidKeySpecException | NoSuchAlgorithmException e) {
            throw new IllegalStateException("Failed to parse public key");
        }}));
```

Much appreciated,
Ania Richardson

**Comment by bdemers** [comment]
@Aniczka which version of Java are you using (version, vendor, os, etc)?

I want to make sure I can test this correctly.

**Comment by Aniczka** [comment]
Details:
Java(TM) SE Runtime Environment (build 1.8.0_181-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.181-b13, mixed mode)
Ubuntu 18.04.3 LTS
Thanks for a quick response!
Ania

**Comment by bdemers** [comment]
@Aniczka I'm still not sure why this failed for you (that is a pretty common env too, very similar to what we previously used for CI)

Either way, removing that extra `.map` step is cleaner, can you take a look at #46 ?

**Comment by Aniczka** [comment]
Thanks! Looks fine! I was surprised too as this would be something very easy to spot!
Let me know when I can pull new library!
Regards,
Ania

**Comment by Aniczka** [comment]
Hi, can you let me know when this fix is expected to be released?
Thanks!
Ania

**Comment by Aniczka** [comment]
Any traction on that? We would like to get a new version that would actually work:/
Thanks!
Ania

**Comment by bdemers** [comment]
@Aniczka sorry for the delay!!
We just pushed a `0.4.1-SNAPSHOT` to https://oss.sonatype.org/content/repositories/snapshots/

Want to give it a quick test?  I want to make sure there isn't something else at play here (I wasn't able to reproduce the error)
Let me know and I'll get a release cut.

**Comment by Aniczka** [comment]
Many thanks! Unfortunately i am getting 403 FORBIDDEN when trying to access URL above.
Request URL:https://oss.sonatype.org/content/repositories/snapshots/
Request Method:GET
Remote Address:54.85.107.240:443
Status Code:
403
Version:HTTP/2.0

**Comment by bdemers** [comment]
@Aniczka I _think_ it's just the directory listings that are disabled (to prevent crawling/DDOS style attacks) are you able to download the artifacts using maven or gradle?

**Comment by Aniczka** [comment]
@bdemers yes,i can do that if you can give me details. Thanks so much for your help!

**Comment by bdemers** [comment]
If you are using Maven, sticking something like this in your ~/.m2/settings.xml should be all you need:
```xml
<profiles>
  <profile>
     <id>allow-snapshots</id>
        <activation><activeByDefault>true</activeByDefault></activation>
     <repositories>
       <repository>
         <id>snapshots-repo</id>
         <url>https://oss.sonatype.org/content/repositories/snapshots</url>
         <releases><enabled>false</enabled></releases>
         <snapshots><enabled>true</enabled></snapshots>
       </repository>
     </repositories>
   </profile>
</profiles>
```

Keep us posted!

**Comment by Aniczka** [comment]
@bdemers what is artifact id? updated settings and tried okta-jwt-verifier and okta-jwt-verifier-java but didn't work.
Thanks a lot!
Ania

**Comment by Aniczka** [comment]
i tried that and okta-jwt-verifier jar was downloaded but not impl where the issue was:
<pluginRepositories>
        <pluginRepository>
            <id>snapshots-repo</id>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
        </pluginRepository>
    </pluginRepositories>
    <dependencies>
        <dependency>
            <groupId>com.okta.jwt</groupId>
            <artifactId>okta-jwt-verifier</artifactId>
            <version>0.4.1-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>com.okta.jwt</groupId>
            <artifactId>okta-jwt-verifier-impl</artifactId>
            <version>0.4.1-SNAPSHOT</version>
        </dependency>
    </dependencies>

**Comment by bdemers** [comment]
Try `<repositories><repository>` instead of `<pluginRepositories><pluginRepository>`

**Comment by Aniczka** [comment]
@bdemers one of those 'i swear it wasn't working before!' moments as i tried repositories before resorting to pluginRepositories! got both now and tested and all is working perfectly now!
Thanks so much!
Ania

**Comment by bdemers** [comment]
Sweet! thanks for following up @Aniczka !
