### ISSUE TITLE
Timeouts in example in README.md is incorrect

### ISSUE THREAD

**Issue by rameshvenk** [okta/okta-jwt-verifier-java#47]
The `setConnectionTimeout(1000)` and `setReadTimeout(1000)` in the example in README.md take a `Duration` instead of an integer. The example should be re-written as follows (assuming the right imports are done elsewhere)

```
Duration timeout = Duration.of(1, ChronoUnit.SECONDS)
```
and change the methods in the builder to
```
setConnectionTimeout(timeout)
setReadTimeout(timeout)
```

**Comment by bdemers** [comment]
Thanks @rameshvenk ! The initial version didn't use Durations, and the README was never fully updated.  I've got a PR open (#48) for this that will pull the code snippet from a source file to make sure it compiles and is accurate.
