### ISSUE TITLE
Use without querying /default/v1/keys ?

### ISSUE THREAD

**Issue by navinpai** [okta/okta-jwt-verifier-java#49]
Hey there,
I was integrating this lib into one of my apps and noticed that this makes use of the `RemoteJwkSigningKeyResolver` which makes an HTTP request to `jwkUri` everytime `getKey()` is called _(via [updateKeys()](https://github.com/okta/okta-jwt-verifier-java/blob/master/impl/src/main/java/com/okta/jwt/impl/jjwt/RemoteJwkSigningKeyResolver.java#L70))_.

Is it possible for me to use the library without making any HTTP requests? It adds a lot of latency to my token verification process.

Does the JSON returned by `https://dev-******.okta.com/oauth2/default/v1/keys` change or can I save it locally and use that instead of querying the HTTP endpoint? 

I know Okta [recommends dynamically querying the endpoint](https://developer.okta.com/docs/reference/api/oidc/#keys), but trying to see if there is a faster way to achieve this.

Thanks for the lib! 😄

**Comment by bdemers** [comment]
Hi @navinpai !

Thanks for checkout out this project.
The keys are cached so the only time a remote request is made is if the key is not cached yet. Depending on key rotation this might only be a couple times per year.

Is there a specific condition you are testing?

**Comment by navinpai** [comment]
I'm unsure if that is the case, since it looks like for every token decode we are doing, the external URL (`/default/v1/keys`) is hit. It's a fairly simply REST API, and is similar to the code below:

```
public String verifyToken(String token) {
    AccessTokenVerifier jwtVerifier = JwtVerifiers.accessTokenVerifierBuilder()
                                                      .setIssuer(ISSUER_URL)
                                                      .setAudience(AUDIENCE)
                                                      .setConnectionTimeout(Duration.ofSeconds(1))
                                                      .setReadTimeout(Duration.ofSeconds(1))
                                                      .build();
    try {
        // This takes 1.5 seconds since it makes a call to Okta everytime
        Jwt jwt = jwtVerifier.decode(accessToken);
        return (String) jwt.getClaims().get("uid"); 
    } catch (JwtVerificationException e) {
          logger.error("local introspect error", e);
          return ERROR;
    }

}
```

I'm unsure why the caching isn't working but every call to the API ends up taking a second or 2 since it makes an external URL call.

Any help with this would be appreciated.

**Comment by bdemers** [comment]
I’ll take a look!

**Comment by donlingliang** [comment]
> I’ll take a look!

@bdemers Could you also take a look if this `keyMap` caching works for multiple threads? Thanks.

**Comment by bdemers** [comment]
reading from multiple threads shouldn't be an issue, but the rare updates may cause additional requests (the current cache mechanism is a bit naive).  Key rotation happens ~4 times a year.

That said the plan is to grab the caching logic from our SDK (and then you could drop in any type of cache you wanted to)

**Comment by donlingliang** [comment]
> reading from multiple threads shouldn't be an issue, but the rare updates may cause additional requests (the current cache mechanism is a bit naive). Key rotation happens ~4 times a year.
> 
> That said the plan is to grab the caching logic from our SDK (and then you could drop in any type of cache you wanted to)

okay, so back to the original question that @navinpai posted, did you find out what causes the rare updates and the solution(manually doing the key rotation may not be a good choice if you already had a better one)?

**Comment by asherzog** [comment]
@bdemers is this issue still being looked at? We have started running into rate limit warnings and violations from Okta for the /keys endpoint because the keys are not caching and requests are being made for every token validation.

**Comment by bdemers** [comment]
@asherzog can you confirm you are using the same instance of `AccessTokenVerifier`/`IdTokenVerifier` each time you are validating a token?

**Comment by navinpai** [comment]
Is that the issue? I've posted the code I'm testing with above: https://github.com/okta/okta-jwt-verifier-java/issues/49#issuecomment-547758291

I create a new `AccessTokenVerifier` for every call to the `verifyToken` method. Should I unstead just use `AccessTokenVerifier` as a class level instance?

**Comment by bdemers** [comment]
@navinpai Yup, that is the issue, reuse that instance to reuse the same cache!
