### ISSUE TITLE
Validating native app's access token throws exception 

### ISSUE THREAD

**Issue by ramkrishs** [okta/okta-jwt-verifier-java#56]
Hi ,

We have a mobile app that authenticates using oidc lib from okta and passes the access token to our resource service part of it’s request call (POST, GET, etc). We have setup an authorization server in our dashboard with default settings and using /oauth2/default endpoint with default audience “api://default”. With this setup, we are using okta’s okta-jwt-verifier-java lib to verify the access token. The problem is we always get `java.lang.IllegalArgumentException: A signing key must be specified if the specified JWT is digitally signed.` When we try to verify the access token. Not sure we made anything wrong here. Is this a bug? 

[Update 1] I tried with nodejs resource api from the sample too i got below error when i tried to verify JWT from the app `Error while resolving signing key for kid "cgtXxWFpMZm3g62lMjRpnwiF2dY4r3mqsBRh2HB9NyM"`

So native app signing the jwt but the okta-jwt-verifier unable to resolve the signature? Am I missing something here? Either this should be a config issue which I missed or there is a bug in the verifier.

[Update 2] I tried to verify a JWT generated by another application which is a java web app. Here I am successfully able to verify the JWT using above node and java services but I am unable to verify the JWT generated only by the android app.

**Comment by bdemers** [comment]
Hey @ramkrishs!

I’m not sure I’m 100% following the problem. Who created the JWT you are trying to verify? Was it Okta? If so what was the issuer URL?  (Or how did you have the native app configured?)
Let us know!

**Comment by ramkrishs** [comment]
I create a native android application with client authentication as PKCE (for public clients)  in okta dashboard. I am using the default authorization server. And that’s the only authorization server.

I am using the android code from the okta documentation to login and generate access token. I am passing that token to a java service which is trying to authorize that access token.

My configuration is as follows for java service:
baseUrl: https://dev-XXX.okta.com
issuer: "https://dev-XXX.okta.com/oauth2/default"
clientId: "<android app 's client id>"
audience: "api://default"

But it fails with the following error message on the java service:
! java.lang.IllegalArgumentException: A signing key must be specified if the specified JWT is digitally signed.
! at io.jsonwebtoken.lang.Assert.notNull(Assert.java:82)
! at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:357)
! at io.jsonwebtoken.impl.DefaultJwtParser.parse(DefaultJwtParser.java:513)
! at com.okta.jwt.impl.jjwt.TokenVerifierSupport.decode(TokenVerifierSupport.java:61

But if i create another application, now instead of native app i create a web application and i use access token generated from that web app. Pass that token to our java service, now our service can decode the JWT and authorize it.

**Comment by ramkrishs** [comment]
I did some more digging apparently for my use case I needed a custom-authorization server which point's to my resource service's url. And it worked. Sorry for my initial hunch on it being a bug. I am closing this issue

**Comment by bdemers** [comment]
@ramkrishs thanks for the follow-up!
