### ISSUE TITLE
Question about Decode and signature verification

### ISSUE THREAD

**Issue by jphines57** [okta/okta-jwt-verifier-java#59]
After I instantiate the JwtVerifier and call decode(jwt) method. Does this method check the JWT signature?

**Comment by bdemers** [comment]
Yup!
The JWT is fully validated (we use the JJWT library under the covers) and this library requires the validation of other claims in Okta Access and ID tokens.  For example, the `iss` and `aud` claim values are required for access tokens.

**Comment by jphines57** [comment]
Awesome! Also, is the best way to verify scopes for client credentials flow to loop over the claims map. Get the scp claim to verify?

**Comment by bdemers** [comment]
Yup! 
And depending on the framework you are using you could bind those scopes to something.  For example, our Spring integration can bind scopes to Spring Authorities

Or if you are making a simple filter, you can just check directly 😄

You can also add custom claims to your tokens: https://developer.okta.com/docs/guides/customize-authz-server/create-claims/

**Comment by jphines57** [comment]
Sweet! I'm attempting to perform the JWT verify in a simple filter prior to routing the API request to the controller endpoint.

**Comment by bdemers** [comment]
Yup!
We have an example [servlet filter](https://github.com/oktadeveloper/okta-legacy-with-cloud-gateway-example/blob/master/legacy-servlet-app/src/main/java/com/okta/example/BearerTokenFilter.java) from a [blog post](https://developer.okta.com/blog/2020/01/08/secure-legacy-spring-cloud-gateway)

That blog post focuses on using Spring Cloud Gateway to deal with the access tokens, (and of course this doesn't just apply to legacy apps), but it sounds like the JWT verification part would be the same for you.

Keep us posted!

**Comment by jphines57** [comment]
So that servlet filter validates the Access Token, but if I'm trying to secure Restful endpoint down to the controller-method level. So how would I verify the access token AND confirm the controller endpoint the client it trying to access is one of the allowed scopes within the claims of the access Token?

Also, on your post here (https://developer.okta.com/blog/2018/04/02/client-creds-with-spring-boot) , I wanted to implement the extra credit but my Spring Boot app is at 2.3.0.RELEASE. Has the okta-spring-boot project been updated to support this version? If not, is it possible to implement the Jwt Verifier separately in it's place? If so, how do I integrate this with this initial demo?

**Comment by bdemers** [comment]
That client credentials post is on my shortlist to update/rewrite with the current version of Spring Boot (and Spring Security).

Honestly, if you are already using Spring Boot, I'd suggest either using the Okta Spring Boot Starter or Spring Security directly.

Our Spring Boot starter is a light wrapper on top of Spring Security and adds the same JWT validation as this project, and it maps a `groups` claim to Spring Authorities automatically (and it works for both Servlet and Reactive stacks).

https://github.com/okta/okta-spring-boot

Spring Security automatically maps the scopes as well, so you could use something like`@PreAuthorize("hasAuthority('SCOPE_your-scope')")`

I'm not sure if i've answered all your questions, or if you want more info on how this project could be would with Spring Security let me know :)

**Comment by jphines57** [comment]
Great information! 
So would it be better to either write a simple filter that does both checks (check accessToken is valid and authorized to the attempted endpoint) OR implement Spring Security to validate the accessToken under the covers and uses the @PreAuthorize("#oauth2.hasScope('customScope')") to authorize method access?
Is one way more secure than the other?

**Comment by bdemers** [comment]
If you are already on Boot, I'd suggest using Spring Security for either option.

If you are thinking about using the client credentials flow between two services, take a look at this video: https://youtu.be/v2J32nd0g24.  Joe talks about a few different patterns that you can use.

But it's hard to suggest which is better without knowing a lot of specifics.  In general, you want to use a token that has the least amount of access you need (mitigating the risk of the leaked token, or misuse by a downstream service)

Also, re the okta-spring-boot should work with the latest version of Spring boot as well.

**Comment by jphines57** [comment]
Thanks, I'll check out that video! I was hoping to use the second option that I suggested previously but I didn't want to call the authorization server to validate the access token each time. How can I avoid all of those calls? 
Also, I understand mitigating risk however what if a client of my service has access to 20 different endpoints. if I was the client I would only want to call the authorization server one time with 20 scopes in order to get back one access token so I only have to manage one token for all of those different endpoints than multiple access token for multiple endpoints. Or did I not understand what you were saying. 😊

**Comment by bdemers** [comment]
Spring Security supports both JWT and opaque access tokens the JWTs are validated locally), and the opaque ones remotely.  

Performance-wise, JWTs (or other locally validated token) would be faster overall because they remove the latency of an additional HTTP request. This comes with the cost of the token could have been revoked by the IdP. (this risk is typically mitigated by keeping the lifespan of the token short)

It's hard to give specific advice without knowing your constraints, and usage patterns.  I was just stating the general "least privilege principle".

**Comment by jphines57** [comment]
I totally understand not knowing the specifics but still trying to give good advice! The basic scenario is I have a service that other third-party clients want to access. So in order to grant access to my service outside of my organization, I'm trying to architect as solution so that I can lock down granular endpoints. 
I was able to get your demo working (

**Comment by bdemers** [comment]
OK, I think I see. In that case, some of what I mentioned might be out of your control. (i.e the number of scopes inbound request).

I'm a fan of using the `@PreAuthoried` annotation, it keeps the access controls close to the code.  You could require authentication (the Spring Security default), and then check access at the method level.  

Alternatively you can also match one layer above this too in a `WebSecurityConfigurerAdapter`, it would look something like:

```java
http.authorizeRequests(authorizedRequest -> {
            authorizedRequest.antMatchers("/my-api/**").hasAuthority("SCOPE_yourCustomScope");
});
```

**NOTE:** I haven't tested this code block ;)
You can find more related details here: https://docs.spring.io/spring-security/site/docs/current/reference/html5/#servlet-authorization-filtersecurityinterceptor

**Comment by arvindkrishnakumar-okta** [comment]
Closing this issue, feel free to reopen if further followup is needed.
