### ISSUE TITLE
Proxy Support Needed

### ISSUE THREAD

**Issue by rahulpratik** [okta/okta-jwt-verifier-java#64]
Can you please update on the release of 0.4.2 version?

**Comment by arvindkrishnakumar-okta** [comment]
@rahulpratik are you specifically looking for any features/bug fixes in `0.4.2`?

**Comment by rahulpratik** [comment]
@arvindkrishnakumar-okta yes I’m looking for the add proxy feature in 0.4.2 version.

**Comment by arvindkrishnakumar-okta** [comment]
@rahulpratik stay tuned, we have this work item planned.

**Comment by rahulpratik** [comment]
@arvindkrishnakumar-okta The proxy support is present in master branch which is pending for 0.4.2 release. It is not present in 0.4.1. Please refer - https://github.com/okta/okta-jwt-verifier-java/blob/okta-jwt-verifier-parent-0.4.1/api/src/main/java/com/okta/jwt/VerifierBuilderSupport.java

**Comment by arvindkrishnakumar-okta** [comment]
@rahulpratik Please use the just released version 0.5.0
