### ISSUE TITLE
Give the developer the ability to set the timeout when accessing the JWKS endpoint

### ISSUE THREAD

**Issue by omgitstom** [okta/okta-jwt-verifier-java#7]
Right now the underlying nimbus library has a default 250ms timeout for accessing the JWKS endpoint.  Customers are running into issues with this timeout value and we need to give the ability to override the default.

https://devforum.okta.com/t/jwt-verification-timeout-java/1074

**Comment by bretjb** [comment]
Hello, we've been running into this issue as well. On the devforum you said you'd start looking into fixing this for the sprint beginning 2018-02-02. I was wondering if there was any updates you can give us? An expected ETA would help us plan accordingly.

Thank you!
