### ISSUE TITLE
Throwing NoSuchMethodError with okta-sdk-java >=3.0.2

### ISSUE THREAD

**Issue by domdomegg** [okta/okta-jwt-verifier-java#80]
### I'm submitting a
  - [x] bug report

### Background info

When installed with okta-sdk-java >= 3.0.2, the id token verifier throws a NoSuchMethodError.

I believe this is probably because the `okta.commons.version` is different between the two libraries (`1.2.4` vs `1.2.5`). The method `HttpClientConfiguration.getRequestExecutorParams` is called but does not exist and so throws a NoSuchMethodError. Potentially related: https://github.com/okta/okta-commons-java/pull/42

### Expected behavior

When creating an id token verifier using the builder, an id token verifier is returned

### What went wrong?

An exception is thrown:

```
NoSuchMethodError: 'Map HttpClientConfiguration.getRequestExecutorParams()'
```

### Steps to reproduce

```
JwtVerifiers.idTokenVerifierBuilder()
          .setClientId("my_client_id")
          .setIssuer("baseurl.okta.com")
          .build();
```

### Library Version

`okta-jwt-verifier`: 0.5.0
`okta-sdk-api`: >= 3.0.2

### Proposed solution

Release a new version of okta-jwt-verifier-java.

`okta.commons.version = 1.2.5` is already set in [the pom](https://github.com/okta/okta-jwt-verifier-java/blob/master/pom.xml#L35), the library just hasn't been released since [16th Sep 2020](https://github.com/okta/okta-jwt-verifier-java/releases/tag/okta-jwt-verifier-parent-0.5.0).

**Comment by bdemers** [comment]
@domdomegg Thanks!

A temporary workaround would be to set the okta commons version in your `pom.xml` dependency management section:

```xml
<dependencyManagement>
        <dependencies>
            <dependency>
                    <groupId>com.okta.commons</groupId>
                    <artifactId>okta-http-okhttp</artifactId>
                    <version>1.2.5</version>
            </dependency>
...
    </dependencies>
</dependencyManagement>
```

(or equivalent Gradle config)


We will get a new version out too ;)

**Comment by arvindkrishnakumar-okta** [comment]
@domdomegg Thanks! We'll get the new version out!

**Comment by domdomegg** [comment]
Amazing, thanks for the quick response both :+1: :raised_hands:
