### ISSUE TITLE
java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtParserBuilder io.jsonwebtoken.Jwts.parserBuilder()'

### ISSUE THREAD

**Issue by er1c** [okta/okta-jwt-verifier-java#95]
On scala:

```scala
libraryDependencies ++= Seq(
  "com.okta.jwt" % "okta-jwt-verifier" % "0.5.1",
  "com.okta.jwt" % "okta-jwt-verifier-impl" % "0.5.1"// % "runtime,test",
)
```

```
[info] com.evenfinancial.auth.oidc.OidcConfigurationSpec *** ABORTED ***
[info]   java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtParserBuilder io.jsonwebtoken.Jwts.parserBuilder()'
[info]   at com.okta.jwt.impl.jjwt.TokenVerifierSupport.buildJwtParser(TokenVerifierSupport.java:50)
[info]   at com.okta.jwt.impl.jjwt.TokenVerifierSupport.<init>(TokenVerifierSupport.java:46)
[info]   at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifier.<init>(JjwtAccessTokenVerifier.java:39)
[info]   at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build(JjwtAccessTokenVerifierBuilder.java:58)
[info]   at com.okta.jwt.impl.jjwt.JjwtAccessTokenVerifierBuilder.build(JjwtAccessTokenVerifierBuilder.java:27)
[info]   at com.evenfinancial.auth.oidc.OidcConfiguration$.accessTokenVerifier(OidcConfiguration.scala:37)
[info]   at com.evenfinancial.auth.oidc.OidcConfiguration$.accessTokenVerifier(OidcConfiguration.scala:29)
[info]   at com.evenfinancial.auth.oidc.OidcConfiguration$.parseToken(OidcConfiguration.scala:19)
[info]   at com.evenfinancial.auth.oidc.OidcConfigurationSpec.$anonfun$new$2(OidcConfigurationSpec.scala:11)
```

Is there a dependency missing in the pom?

**Comment by er1c** [comment]
Fixed by adding:

```
  "io.jsonwebtoken" % "jjwt-api" % "0.11.2" % "runtime,test",
  "io.jsonwebtoken" % "jjwt-impl" % "0.11.2" % "runtime,test",
```

not ideal.

**Comment by bdemers** [comment]
Hi @er1c!

It’s been a while since I’ve done any Scala, but it a sounds like it’s a Scala build tool issue when pulling in dependencies?

‘jjwt-impl’ is a runtime scoped dependency of  this project, so it _should_ get pulled in the same way. 

Any chance you can put together a minimal example that reproduces the problem?

**Comment by er1c** [comment]
@bdemers https://github.com/er1c/okta-jwt-verifier-scala-example/blob/main/build.sbt here you go!

**Comment by er1c** [comment]
@bdemers is the library just missing as a `<dependency>` https://github.com/okta/okta-jwt-verifier-java/blob/master/pom.xml#L36 ?

**Comment by er1c** [comment]
Hmm: https://gist.github.com/er1c/2fc4a587ff54bbe719546b1b92bf6c7c this is working, let me close this for now and see if I run into the same issue again.

**Comment by bdemers** [comment]
Thanks for following up @er1c.  Let us know if you figure out where the issue was!

**Comment by hscabral** [comment]
Hey folks, I ended up here after searching for the same error in a Gradle build:

```Caused by: java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtParserBuilder io.jsonwebtoken.Jwts.parserBuilder()'```

My Gradle Okta block looks like this:

```

**Comment by hscabral** [comment]
Hey folks, I ended up here after searching for the same error in a Gradle build:

Caused by: java.lang.NoSuchMethodError: 'io.jsonwebtoken.JwtParserBuilder io.jsonwebtoken.Jwts.parserBuilder()'

My Gradle Okta block looks like this:
```
    // Okta SSO / SAML
    implementation 'com.okta.spring:okta-spring-boot-starter:2.1.5'
    implementation 'com.okta.jwt:okta-jwt-verifier:0.5.1'
    implementation 'com.okta.jwt:okta-jwt-verifier-impl:0.5.1'
```

I've tried adding the explicit JJWT deps, but with the same results. Any hints here?

**Comment by mwisnicki** [comment]
I think the problem was caused by old version of `play-ws` pulling `jjwt` but okta uses newer version that was renamed to `jjwt-impl`. Depending on classpath ordering, old version lacking necessary methods would be loaded first.

SBT doesn't realize it's the same dependency due to rename.
