### ISSUE TITLE
Convert integration tests to java

### ISSUE THREAD

**Issue by er1c** [okta/okta-jwt-verifier-java#96]
I see https://github.com/okta/okta-jwt-verifier-java/blob/master/integration-tests/src/test/groovy/com/okta/jwt/it/KeyServerITSupport.groovy

and want to use something like this for my own unit/integration tests - can this be refactored into java code and packaged as a jar/package suitable for unit tests for this library?

**Comment by bdemers** [comment]
Hi @er1c!

Your best bet would be to copy the classes into your own project.

We watch for API compatibility (semver) very carefully. Adding an external facing test module would require us to manage that the same way, which would make it harder to refactor theses tests if/when needed.

That said! It a lot of folks feel this way it might be something we should consider. 

Anyone else that sees this issue please give it a 👍 if you would like to see this functionality.

**Comment by er1c** [comment]
I semi-created scala versions here: https://github.com/er1c/okta-jwt-verifier-scala-example/blob/main/build.sbt

**Comment by arvindkrishnakumar-okta** [comment]
We will close this ticket as we would like to keep the tests in Groovy like we already have in most other Java repos for the consistency sake.
