### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by er1c** [okta/okta-jwt-verifier-java#98]
### I'm submitting a
  - [ ] bug report
  - [x] feature request

### Background info

It's not directly obvious how to configure the http client requests to an issuer URL using a `Future` other than wrapping them in my own task runner.

### Expected behavior

I would like: 

* `Future<Jwt> jwtFuture = jwtVerifier.asyncDecode(jwtString);`
* `setExecutor(Executor executor)` in `AccessTokenVerifier.Builder`

**Comment by arvindkrishnakumar-okta** [comment]
@er1c Thanks for posting!

While it sounds like a nice API to add to the framework, on giving it a deeper thought I feel like this level of multi threading capability is better handled flexibly at the client side (as the library user/client) and not at the framework level.

**Comment by arvindkrishnakumar-okta** [comment]
@er1c Sure, that is by design as we didn't feel the need to expose the HTTP client params.

**Comment by arvindkrishnakumar-okta** [comment]
@er1c your comment is noted and Readme is updated.
